FROM node:21

# Set the working directory
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json (if available)
COPY package*.json tsconfig*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application source code
COPY dist/ dist/

# Command to run the application
CMD ["npm", "run", "start:prod"]

