version: '3.1'

services:
  client: 
    build: 
      context: ./client
      dockerfile: dockerfile # Указываем путь к Dockerfile
    ports:
      - "3030:3030"
    depends_on:
      - db_users
      - db_comments
      
    environment:
      USER_SERVICE_HOST: user_service
      USER_SERVICE_PORT: 9999
      COMMENT_SERVICE_HOST: comment_service
      COMMENT_SERVICE_PORT: 9998

    networks:
      - backend

  user_service: 
    build: 
      context: ./users
      dockerfile: dockerfile # Указываем путь к Dockerfile
      
    environment:
      jwt_secret: SECRET
      
    ports:
      - "9999:9999"
    depends_on:
      - db_users
    networks:
      - backend
      - backend_users

  comment_service: 
    build: 
      context: ./comments
      dockerfile: dockerfile # Указываем путь к Dockerfile
      
    ports:
      - "9998:9998"
    depends_on:
      - db_comments
    networks:
      - backend
      - backend_comments

  db_users:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: user
    ports:
      - "3307:3306"
    volumes:
      - ./containers/mysql_users:/var/lib/mysql
    networks:
      - backend_users
  
  db_comments:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: comment
    ports:
      - 3306:3306
    volumes:
      - ./containers/mysql_comments:/var/lib/mysql
    networks:
      - backend_comments


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
    networks:
      - backend
      - backend_users
      - backend_comments

networks:
  backend:
    driver: bridge
  backend_comments:
    driver: bridge
  backend_users:
    driver: bridge



